apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels:
    app: nginx
    type: frontend
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
